// SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity 0.8.9;

// Auto-generated by scripts/prepare.ts for chainId 42161 — SushiSwap (Arbitrum mainnet).
// DO NOT edit by hand. Run `npx hardhat run scripts/prepare.ts --network livenet`
// to regenerate for a different chain (config in scripts/delegate-configs.ts).

address constant DELEGATE_FACTORY = 0xc35DADB65012eC5796536bD9864eD8773aBc74C4; // SushiSwap (Arbitrum mainnet)

bytes constant DELEGATE_INIT_CODE_HASH = hex"e18a34eb0e04b04f7a0ac29a6e80748dca96319b42c54d679cb821dca90c6303"; // SushiSwap (Arbitrum mainnet)

uint256 constant DELEGATE_NET_FEE = 9970; // SushiSwap (Arbitrum mainnet)

bool constant DELEGATE_CREATE2_ZKSYNC = false;

bool constant DELEGATE_VELODROME = false;
