/**
 * Pre-deploy preparation script.
 *
 * Replaces manual edits of `Delegation.sol` and `UniswapV2Library.sol` that the
 * old workflow required for each new chain. Run BEFORE `deploy.ts`.
 *
 * Flow:
 *   1. Read target chainId (via hardhat network config).
 *   2. Look up delegate config in `scripts/delegate-configs.ts`.
 *   3. Rewrite `contracts/core/Delegation.sol` with those constants.
 *   4. Compile once — this produces the UniswapV2Pair artifact with the new
 *      DELEGATE constants baked in.
 *   5. Read the Pair creationCode hash from the artifact.
 *   6. Rewrite `contracts/periphery/libraries/UniswapV2Library.sol` with that hash.
 *   7. Compile again — Router now has the correct `pairFor` derivation.
 *
 * After this runs, `deploy.ts` can execute without touching Solidity source.
 *
 * Usage:
 *   $env:NETWORK = "mainnet"
 *   $env:ALCHEMY_KEY = "..."
 *   npx hardhat run scripts/prepare.ts --network livenet
 */

import fs from 'fs';
import path from 'path';
import hardhat from 'hardhat';
import { ethers } from 'ethers';
import { getDelegateConfig } from './delegate-configs';
import { initialize } from './library';

const DELEGATION_PATH = path.join(__dirname, '..', 'contracts', 'core', 'Delegation.sol');
const LIBRARY_PATH = path.join(__dirname, '..', 'contracts', 'periphery', 'libraries', 'UniswapV2Library.sol');

function generateDelegationSource(chainId: number): string {
  const c = getDelegateConfig(chainId);
  return `// SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity 0.8.9;

// Auto-generated by scripts/prepare.ts for chainId ${chainId} — ${c.dexName}.
// DO NOT edit by hand. Run \`npx hardhat run scripts/prepare.ts --network livenet\`
// to regenerate for a different chain (config in scripts/delegate-configs.ts).

address constant DELEGATE_FACTORY = ${c.factory}; // ${c.dexName}

bytes constant DELEGATE_INIT_CODE_HASH = hex"${c.initCodeHash.replace(/^0x/, '')}"; // ${c.dexName}

uint256 constant DELEGATE_NET_FEE = ${c.netFee}; // ${c.dexName}

bool constant DELEGATE_CREATE2_ZKSYNC = ${c.createZksync};

bool constant DELEGATE_VELODROME = ${c.velodrome};
`;
}

function patchLibraryInitCodeHash(newHash: string): void {
  const contents = fs.readFileSync(LIBRARY_PATH, 'utf8');
  const clean = newHash.replace(/^0x/, '').toLowerCase();
  const marker = /hex"[0-9a-fA-F]{64}" \/\/ init code hash/;
  if (!marker.test(contents)) {
    throw new Error('Could not locate init code hash marker in UniswapV2Library.sol');
  }
  const replaced = contents.replace(marker, `hex"${clean}" // init code hash`);
  if (replaced === contents) return; // hash already up to date, no-op
  fs.writeFileSync(LIBRARY_PATH, replaced);
}

async function readPairInitCodeHash(): Promise<string> {
  const artifact = await hardhat.artifacts.readArtifact('UniswapV2Pair');
  const bytecode = artifact.bytecode;
  if (!bytecode || bytecode === '0x') throw new Error('UniswapV2Pair artifact has no bytecode');
  return ethers.utils.keccak256(bytecode);
}

async function main(): Promise<void> {
  const { chainId } = await initialize();
  console.log('Preparing contracts for chainId ' + chainId + '...');

  const config = getDelegateConfig(chainId);
  console.log('Delegate DEX: ' + config.dexName);
  console.log('  factory        = ' + config.factory);
  console.log('  initCodeHash   = ' + config.initCodeHash);
  console.log('  netFee         = ' + config.netFee);
  console.log('  createZksync   = ' + config.createZksync);
  console.log('  velodrome      = ' + config.velodrome);

  console.log();
  console.log('[1/4] Writing Delegation.sol...');
  fs.writeFileSync(DELEGATION_PATH, generateDelegationSource(chainId));

  console.log('[2/4] Compiling to generate Pair artifact...');
  await hardhat.run('compile');

  console.log('[3/4] Extracting Pair initCodeHash from artifact...');
  const pairHash = await readPairInitCodeHash();
  console.log('  initCodeHash(Pair) = ' + pairHash);
  patchLibraryInitCodeHash(pairHash);
  console.log('  -> UniswapV2Library.sol updated');

  console.log('[4/4] Recompiling with patched library...');
  await hardhat.run('compile');

  console.log();
  console.log('Prepare complete. You may now run:');
  console.log('  npx hardhat run scripts/deploy.ts --network livenet');
}

main()
  .then(() => process.exit(0))
  .catch((e) => { console.error(e); process.exit(1); });
